name: pull-request
run-name: testing
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run script
        run: |
          index.js > README.md
